import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    // <html className='font-sans bg-slate-500 text-2xl'>
    <div className='font-sans bg-slate-500 text-2xl'>
      <Head>
        <title>Miyu's Links</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <header className='flex flex-col items-center my-12 text-white text-center'>
          <img src='/Lily2.png' className='w-36 rounded-full border-2 border-white'/>
          <h1 className='inline-block p-2'>hi, I'm Miyu</h1>
        </header>

        <ul className='border-5 border-white w-28 text-center'>
          <li className='bg-black'>
            <a href="https://github.com/0xmiyu" target="_blank"> Github </a>
          </li>
          <li>
            <a href="https://www.linkedin.com/in/martinongyj/" target="_blank"> LinkedIn </a>
          </li>
          <li>
           <a href="https://martinongyj.com" target="_blank"> Website </a>
          </li>
          <li>
            <a href="./images/Martin Ong's Resume.pdf" download> Resume Download </a>
          </li>
        </ul>

      </main>
    </div>

  )
}
