import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='font-sans bg-slate-500 text-2xl h-screen'>
      <Head>
        <title>Miyu's Links</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <header className='flex flex-col items-center text-white text-center'>
          <img src='/Lily2.png' className='w-36 rounded-full border-2 border-white my-10'/>
          <h1 className='inline-block p-2'>hi, I'm Miyu</h1>
        </header>

        <ul className='font-mono text-xl table m-auto border-5 border-white w-32 text-center'>
          <li className='m-2 bg-black rounded-lg hover:bg-gray-300 hover:text-black'>
            <a href="https://github.com/0xmiyu" target="_blank"> Github </a>
          </li>
          <li className='m-2 bg-black rounded-lg hover:bg-gray-300 hover:text-black'>
            <a href="https://www.linkedin.com/in/martinongyj/" target="_blank"> LinkedIn </a>
          </li>
          <li className='m-2 bg-black rounded-lg hover:bg-gray-300 hover:text-black'>
           <a href="https://martinongyj.com" target="_blank"> Website </a>
          </li >
          <li className='m-2 bg-black rounded-lg hover:bg-gray-300 hover:text-black'>
            <a href="./images/Martin Ong's Resume.pdf" download> Resume </a>
          </li>
        </ul>

      </main>
    </div>

  )
}
