import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { BsGithub, BsLinkedin, BsTelegram, BsTwitter } from "react-icons/bs";
import {AiOutlineMail} from "react-icons/ai"

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <div className="bg-gray-900 text-2xl h-screen">
            <Head>
                <title>Miyu&apos;s Links</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <header className="flex flex-col items-center text-white text-center">
                    <img
                        src="/madlads.png"
                        className="w-36 rounded-full border-2 border-white mt-10"
                    />
                    <h1 className="inline-block pt-1 pb-5">hi, I&apos;m Martin</h1>
                </header>

                <div className="flex items-center justify-center">
                    <ul className="font-mono text-xl table border-5 border-white w-7/12 text-center">
                        <li className="p-3 my-2 mx-4 bg-black rounded-lg hover:bg-gray-300 hover:text-black">
                            <div className="flex items-center">
                                <BsGithub className="ml-auto" />

                                <a
                                    href="https://github.com/0xmiyu"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="flex-1 text-center"
                                >
                                    Github
                                </a>
                            </div>
                        </li>
                        <li className="p-3 mb-2 mx-4 bg-black rounded-lg hover:bg-gray-300 hover:text-black">
                            <div className="flex items-center">
                                <BsLinkedin className="ml-auto" />
                                <a
                                    href="https://www.linkedin.com/in/martinongyj/"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="flex-1 text-center"
                                >
                                    LinkedIn
                                </a>
                            </div>
                        </li>
                        
                        <li className="p-3 mb-4 mx-4 bg-black rounded-lg hover:bg-gray-300 hover:text-black">
                            <div className="flex items-center">
                                <BsTwitter className="ml-auto" />
                                <a
                                    href="https://twitter.com/0xmiyu"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="flex-1 text-center"
                                >
                                    Twitter
                                </a>
                            </div>
                        </li>
                        <li className="p-3 mb-4 bg-gray-800 rounded-3xl hover:bg-gray-300 hover:text-black">
                            <div className="flex items-center">
                                <BsTelegram className="ml-4" />
                                <a
                                    href="https://t.me/miyu_sol"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="flex-1 text-center"
                                >
                                    Telegram
                                </a>
                            </div>
                        </li>
                        <li className="p-3 mb-2 bg-gray-800 rounded-3xl hover:bg-gray-300 hover:text-black">
                            <div className="flex items-center">
                                <AiOutlineMail className="ml-4" />
                                <a
                                    href="mailto:ong.martin24@gmail.com"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="flex-1 text-center"
                                >
                                    Email
                                </a>
                            </div>
                        </li>
                        {/*
                        <li className="p-2 mb-2 bg-black rounded-lg hover:bg-gray-300 hover:text-black">
                            <a
                                href="https://martinongyj.com"
                                target="_blank"
                                rel="noopener noreferrer"
                            >
                                Website
                            </a>
                        </li>
                        <li className="p-2 mb-2 bg-black rounded-lg hover:bg-gray-300 hover:text-black">
                            <a href="./images/Martin Ong's Resume.pdf" download>
                                Resume
                            </a>
                        </li>
                        */}
                    </ul>
                </div>
            </main>
        </div>
    );
}
